#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $AUTH_DB_USER WITH PASSWORD '$AUTH_DB_PASSWORD';
    CREATE DATABASE $AUTH_DB_NAME OWNER $AUTH_DB_USER;
    GRANT ALL PRIVILEGES ON DATABASE $AUTH_DB_NAME TO $AUTH_DB_USER;
EOSQL
