// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	application "github.com/illia-malachyn/food-delivery/order/application"
	mock "github.com/stretchr/testify/mock"
)

// EventUpcaster is an autogenerated mock type for the EventUpcaster type
type EventUpcaster struct {
	mock.Mock
}

type EventUpcaster_Expecter struct {
	mock *mock.Mock
}

func (_m *EventUpcaster) EXPECT() *EventUpcaster_Expecter {
	return &EventUpcaster_Expecter{mock: &_m.Mock}
}

// Upcast provides a mock function with given fields: events
func (_m *EventUpcaster) Upcast(events []application.IntegrationEvent) []application.IntegrationEvent {
	ret := _m.Called(events)

	if len(ret) == 0 {
		panic("no return value specified for Upcast")
	}

	var r0 []application.IntegrationEvent
	if rf, ok := ret.Get(0).(func([]application.IntegrationEvent) []application.IntegrationEvent); ok {
		r0 = rf(events)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]application.IntegrationEvent)
		}
	}

	return r0
}

// EventUpcaster_Upcast_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upcast'
type EventUpcaster_Upcast_Call struct {
	*mock.Call
}

// Upcast is a helper method to define mock.On call
//   - events []application.IntegrationEvent
func (_e *EventUpcaster_Expecter) Upcast(events interface{}) *EventUpcaster_Upcast_Call {
	return &EventUpcaster_Upcast_Call{Call: _e.mock.On("Upcast", events)}
}

func (_c *EventUpcaster_Upcast_Call) Run(run func(events []application.IntegrationEvent)) *EventUpcaster_Upcast_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]application.IntegrationEvent))
	})
	return _c
}

func (_c *EventUpcaster_Upcast_Call) Return(_a0 []application.IntegrationEvent) *EventUpcaster_Upcast_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EventUpcaster_Upcast_Call) RunAndReturn(run func([]application.IntegrationEvent) []application.IntegrationEvent) *EventUpcaster_Upcast_Call {
	_c.Call.Return(run)
	return _c
}

// NewEventUpcaster creates a new instance of EventUpcaster. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventUpcaster(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventUpcaster {
	mock := &EventUpcaster{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
