// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// IntegrationEvent is an autogenerated mock type for the IntegrationEvent type
type IntegrationEvent struct {
	mock.Mock
}

type IntegrationEvent_Expecter struct {
	mock *mock.Mock
}

func (_m *IntegrationEvent) EXPECT() *IntegrationEvent_Expecter {
	return &IntegrationEvent_Expecter{mock: &_m.Mock}
}

// AggregateID provides a mock function with no fields
func (_m *IntegrationEvent) AggregateID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for AggregateID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// IntegrationEvent_AggregateID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AggregateID'
type IntegrationEvent_AggregateID_Call struct {
	*mock.Call
}

// AggregateID is a helper method to define mock.On call
func (_e *IntegrationEvent_Expecter) AggregateID() *IntegrationEvent_AggregateID_Call {
	return &IntegrationEvent_AggregateID_Call{Call: _e.mock.On("AggregateID")}
}

func (_c *IntegrationEvent_AggregateID_Call) Run(run func()) *IntegrationEvent_AggregateID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IntegrationEvent_AggregateID_Call) Return(_a0 string) *IntegrationEvent_AggregateID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IntegrationEvent_AggregateID_Call) RunAndReturn(run func() string) *IntegrationEvent_AggregateID_Call {
	_c.Call.Return(run)
	return _c
}

// AggregateType provides a mock function with no fields
func (_m *IntegrationEvent) AggregateType() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for AggregateType")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// IntegrationEvent_AggregateType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AggregateType'
type IntegrationEvent_AggregateType_Call struct {
	*mock.Call
}

// AggregateType is a helper method to define mock.On call
func (_e *IntegrationEvent_Expecter) AggregateType() *IntegrationEvent_AggregateType_Call {
	return &IntegrationEvent_AggregateType_Call{Call: _e.mock.On("AggregateType")}
}

func (_c *IntegrationEvent_AggregateType_Call) Run(run func()) *IntegrationEvent_AggregateType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IntegrationEvent_AggregateType_Call) Return(_a0 string) *IntegrationEvent_AggregateType_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IntegrationEvent_AggregateType_Call) RunAndReturn(run func() string) *IntegrationEvent_AggregateType_Call {
	_c.Call.Return(run)
	return _c
}

// EventName provides a mock function with no fields
func (_m *IntegrationEvent) EventName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for EventName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// IntegrationEvent_EventName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EventName'
type IntegrationEvent_EventName_Call struct {
	*mock.Call
}

// EventName is a helper method to define mock.On call
func (_e *IntegrationEvent_Expecter) EventName() *IntegrationEvent_EventName_Call {
	return &IntegrationEvent_EventName_Call{Call: _e.mock.On("EventName")}
}

func (_c *IntegrationEvent_EventName_Call) Run(run func()) *IntegrationEvent_EventName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IntegrationEvent_EventName_Call) Return(_a0 string) *IntegrationEvent_EventName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IntegrationEvent_EventName_Call) RunAndReturn(run func() string) *IntegrationEvent_EventName_Call {
	_c.Call.Return(run)
	return _c
}

// EventOccurredAt provides a mock function with no fields
func (_m *IntegrationEvent) EventOccurredAt() time.Time {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for EventOccurredAt")
	}

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// IntegrationEvent_EventOccurredAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EventOccurredAt'
type IntegrationEvent_EventOccurredAt_Call struct {
	*mock.Call
}

// EventOccurredAt is a helper method to define mock.On call
func (_e *IntegrationEvent_Expecter) EventOccurredAt() *IntegrationEvent_EventOccurredAt_Call {
	return &IntegrationEvent_EventOccurredAt_Call{Call: _e.mock.On("EventOccurredAt")}
}

func (_c *IntegrationEvent_EventOccurredAt_Call) Run(run func()) *IntegrationEvent_EventOccurredAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IntegrationEvent_EventOccurredAt_Call) Return(_a0 time.Time) *IntegrationEvent_EventOccurredAt_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IntegrationEvent_EventOccurredAt_Call) RunAndReturn(run func() time.Time) *IntegrationEvent_EventOccurredAt_Call {
	_c.Call.Return(run)
	return _c
}

// EventVersion provides a mock function with no fields
func (_m *IntegrationEvent) EventVersion() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for EventVersion")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// IntegrationEvent_EventVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EventVersion'
type IntegrationEvent_EventVersion_Call struct {
	*mock.Call
}

// EventVersion is a helper method to define mock.On call
func (_e *IntegrationEvent_Expecter) EventVersion() *IntegrationEvent_EventVersion_Call {
	return &IntegrationEvent_EventVersion_Call{Call: _e.mock.On("EventVersion")}
}

func (_c *IntegrationEvent_EventVersion_Call) Run(run func()) *IntegrationEvent_EventVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IntegrationEvent_EventVersion_Call) Return(_a0 int) *IntegrationEvent_EventVersion_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IntegrationEvent_EventVersion_Call) RunAndReturn(run func() int) *IntegrationEvent_EventVersion_Call {
	_c.Call.Return(run)
	return _c
}

// NewIntegrationEvent creates a new instance of IntegrationEvent. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIntegrationEvent(t interface {
	mock.TestingT
	Cleanup(func())
}) *IntegrationEvent {
	mock := &IntegrationEvent{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
