// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	application "github.com/illia-malachyn/food-delivery/order/application"
	domain "github.com/illia-malachyn/food-delivery/order/domain"
	mock "github.com/stretchr/testify/mock"
)

// OrderRepository is an autogenerated mock type for the OrderRepository type
type OrderRepository struct {
	mock.Mock
}

type OrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderRepository) EXPECT() *OrderRepository_Expecter {
	return &OrderRepository_Expecter{mock: &_m.Mock}
}

// GetOrderById provides a mock function with given fields: ctx, id
func (_m *OrderRepository) GetOrderById(ctx context.Context, id string) (*domain.Order, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderById")
	}

	var r0 *domain.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Order, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Order); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderRepository_GetOrderById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderById'
type OrderRepository_GetOrderById_Call struct {
	*mock.Call
}

// GetOrderById is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *OrderRepository_Expecter) GetOrderById(ctx interface{}, id interface{}) *OrderRepository_GetOrderById_Call {
	return &OrderRepository_GetOrderById_Call{Call: _e.mock.On("GetOrderById", ctx, id)}
}

func (_c *OrderRepository_GetOrderById_Call) Run(run func(ctx context.Context, id string)) *OrderRepository_GetOrderById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *OrderRepository_GetOrderById_Call) Return(_a0 *domain.Order, _a1 error) *OrderRepository_GetOrderById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderRepository_GetOrderById_Call) RunAndReturn(run func(context.Context, string) (*domain.Order, error)) *OrderRepository_GetOrderById_Call {
	_c.Call.Return(run)
	return _c
}

// SaveOrder provides a mock function with given fields: ctx, order, events
func (_m *OrderRepository) SaveOrder(ctx context.Context, order *domain.Order, events []application.IntegrationEvent) error {
	ret := _m.Called(ctx, order, events)

	if len(ret) == 0 {
		panic("no return value specified for SaveOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Order, []application.IntegrationEvent) error); ok {
		r0 = rf(ctx, order, events)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrderRepository_SaveOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveOrder'
type OrderRepository_SaveOrder_Call struct {
	*mock.Call
}

// SaveOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order *domain.Order
//   - events []application.IntegrationEvent
func (_e *OrderRepository_Expecter) SaveOrder(ctx interface{}, order interface{}, events interface{}) *OrderRepository_SaveOrder_Call {
	return &OrderRepository_SaveOrder_Call{Call: _e.mock.On("SaveOrder", ctx, order, events)}
}

func (_c *OrderRepository_SaveOrder_Call) Run(run func(ctx context.Context, order *domain.Order, events []application.IntegrationEvent)) *OrderRepository_SaveOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Order), args[2].([]application.IntegrationEvent))
	})
	return _c
}

func (_c *OrderRepository_SaveOrder_Call) Return(_a0 error) *OrderRepository_SaveOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderRepository_SaveOrder_Call) RunAndReturn(run func(context.Context, *domain.Order, []application.IntegrationEvent) error) *OrderRepository_SaveOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderRepository creates a new instance of OrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderRepository {
	mock := &OrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
