#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $PAYMENT_DB_USER WITH PASSWORD '$PAYMENT_DB_PASSWORD';
    ALTER ROLE $PAYMENT_DB_USER WITH REPLICATION;
    CREATE DATABASE $PAYMENT_DB_NAME OWNER $PAYMENT_DB_USER;
    GRANT ALL PRIVILEGES ON DATABASE $PAYMENT_DB_NAME TO $PAYMENT_DB_USER;
EOSQL
