#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $RESTAURANT_DB_USER WITH PASSWORD '$RESTAURANT_DB_PASSWORD';
    CREATE DATABASE $RESTAURANT_DB_NAME OWNER $RESTAURANT_DB_USER;
    GRANT ALL PRIVILEGES ON DATABASE $RESTAURANT_DB_NAME TO $RESTAURANT_DB_USER;
EOSQL
