// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DomainEvent is an autogenerated mock type for the DomainEvent type
type DomainEvent struct {
	mock.Mock
}

type DomainEvent_Expecter struct {
	mock *mock.Mock
}

func (_m *DomainEvent) EXPECT() *DomainEvent_Expecter {
	return &DomainEvent_Expecter{mock: &_m.Mock}
}

// EventName provides a mock function with no fields
func (_m *DomainEvent) EventName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for EventName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// DomainEvent_EventName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EventName'
type DomainEvent_EventName_Call struct {
	*mock.Call
}

// EventName is a helper method to define mock.On call
func (_e *DomainEvent_Expecter) EventName() *DomainEvent_EventName_Call {
	return &DomainEvent_EventName_Call{Call: _e.mock.On("EventName")}
}

func (_c *DomainEvent_EventName_Call) Run(run func()) *DomainEvent_EventName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DomainEvent_EventName_Call) Return(_a0 string) *DomainEvent_EventName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DomainEvent_EventName_Call) RunAndReturn(run func() string) *DomainEvent_EventName_Call {
	_c.Call.Return(run)
	return _c
}

// NewDomainEvent creates a new instance of DomainEvent. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDomainEvent(t interface {
	mock.TestingT
	Cleanup(func())
}) *DomainEvent {
	mock := &DomainEvent{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
