#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $DELIVERY_DB_USER WITH PASSWORD '$DELIVERY_DB_PASSWORD';
    CREATE DATABASE $DELIVERY_DB_NAME OWNER $DELIVERY_DB_USER;
    GRANT ALL PRIVILEGES ON DATABASE $DELIVERY_DB_NAME TO $DELIVERY_DB_USER;
EOSQL
